### ISSUE TITLE
All images being unconditionally upscaled

### ISSUE THREAD

**Issue by johnbillion** [cftp/upscale#1]
As we've seen on the ES site, Upscale is upscaling all images all the time. This means images such as logos uploaded through the customiser are being upscaled when we don't want them to be.

Ideally we'd introduce a new image size for upscaled images, instead of upscaling the original file.

Off the top of my head I'm not sure where we'll need to hook into in order to create our upscaled image for one image size. I'll look into it.

**Comment by tomjn** [comment]
If i upload a 600x600px image, my thumbnails are not 600x600, what the plugin does is increase the images resolution before it gets to that stage.

From my understanding then, if you get a 500x500 logo when uploading a 500x500 image, then you should have a logo image size. Otherwise the plugin is useless unless the theme goes to extra lengths to check for the size of the image and then use the upscaled version and all the complicatedness that ensues.
